development:
  adapter: postgresql
  database: alive_fulfillment_app_development
  pool: 5
  username: alive_fulfillment_app
  password:
test:
  adapter: postgresql
  database: alive_fulfillment_app_test
  pool: 5
  username: alive_fulfillment_app
  password:
production:
  adapter: postgresql
  database: alive_fulfillment_app_production
  pool: 5
  username: alive_fulfillment_app
  password:
